[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "penalty subject wrist apology dawn bulk stable response village doll gauge like rookie pulp scissors pen mercy crowd negative return fee typical visa erupt"
